### PR TITLE
Some ScoiaTael Copper

### PR DESCRIPTION
**Pull request by LieToMe7702**

### CODE REVIEW

**Comment by LieToMe7702** [comment]
添加了大部分松鼠党铜卡，缺少战舞者、精灵斥候，以及维旅赫德旅的所有铜卡

**Comment by LieToMe7702** [comment]
1.去除了无用的异步方法重写
2.自动流程焚烧陷阱配置有问题
3.玛哈坎劫掠者上次提交就已经限制了，见方法重载，代码的直接引用不应该超过两级
ps:最好添加一个用于部署的环境，忽略代码生成的dll提交，否则难以处理冲突

**Comment by AlseinX** [comment]
There is unlikely to be a way to hook into the Unity project build pipeline, thats why common assemblies are directly placed without any script.

**Comment by LieToMe7702** [comment]
脚本只是用来替代你手动替换的过程，和怎么依赖引用没有关系，和是不是unity项目更加没有关系。我的意思不是你直接引用代码，而是git同步忽略dll，部署的时候再根据最新的代码自动生成dll，以避免冲突。

**Comment by AlseinX** [comment]
Yeah a script on this scope is surely helpful but it could be really hard to track the indirect dependencies for each nuget package within a bash script, or an executable project is needed to implement it.

**Comment by AlseinX** [comment]
Join [Slack](https://legacygwent.slack.com/) for discussion.

**Comment by LieToMe7702** [comment]
哪个键不小心按错了，reshaper自己加的吧，没有注意，应该是无用的引用

**Comment by AlseinX** [comment]
Remove them and this PR is considered ready to merge, and confirm merging by removing `[WIP]` prefix from the title.

**Pull request merged**
