### PR TITLE
[WIP] Discard Expansion

### PR DESCRIPTION
**Pull request by Pippow**
This PR aims to add several cards to support the discard archetype.
Currently only the following card has been coded: An Crate Warlord: Skellige - Bronze - Soldier - Clan An Crate - 6 strength - while in hand, deck or on the board, boost by 1 every time you discard a card 
This is my first PR ever, I would be very grateful if someone knowledgeable could review it and tell me if I need to change something or if I can go on and add the other cards, thanks!

### CODE REVIEW

**Comment by neal2018** [comment]
Hey, thanks for contributing. Here are some notes.

1. To add new card picture you need to put the file in https://github.com/LegacyGwent/LegacyGwent/tree/diy/src/Cynthia.Card.Unity/src/Cynthia.Unity.Card/Assets/Addressables/Cards
2. to support multiple languages, you also need to modify files in https://github.com/LegacyGwent/LegacyGwent/tree/diy/src/Cynthia.Card/src/Cynthia.Card.Server/Locales
3. To let users received the app day you also need to increase the version here. https://github.com/LegacyGwent/LegacyGwent/blob/diy/src/Cynthia.Card/src/Cynthia.Card.Common/GwentGame/GwentMap.cs#L11 Just increasing by one should be fine
4. Also, before you merge the new card, please make sure you discuss it widely in the community and most people in the community  agree with adding it

Again, thanks for contributing! I think you did a great job as a beginner press. Let me know if you need more help!!

**Comment by Pippow** [comment]
Hi Neal, thanks a lot for the help!
1. Can you please give me push access so I can upload new arts? There were some nice recent Homecoming artworks that inspired me. I can do without for the moment though, you have already uploaded plenty of material.
2. & 3. Will look into it, thanks
4. All cards were widely discussed in the DIY discord channel, where they got several positive responses. Is there anywhere else I should post to include more people? How does balance decision process work by the way?

**Comment by neal2018** [comment]
As for pictures, you can just include them in your own branch, and include  them together in this PR.

As for the balance decision process, I have to say there is really no balance decision process 🥲 Currently, as long as someone wrote the code, and I or other maintainers think community is happy with that, they can all get merged

**Comment by neal2018** [comment]
Oh! By the way, please merge your branch into diy branch instead of master branch!
01876889-F114-45D8-A11C-83E6B77011CF

**Pull request closed without merging**
